name: Render Deploy

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ttskch/render-deploy@v1.0.0
        with:
          api-key: ${{ secrets.RENDER_PASSWORD }}
          service-id: ${{ secrets.RENDER_EMAIL }}
          interval: 20 # optional
          timeout: 300 # optional
